language: ruby
cache: bundler
sudo: false
notifications:
  email: false
rvm:
- 2.3.1
before_install: gem install bundler
env:
  global:
    secure: YgwpSV66h+QXujg6oAihWW2U1MXuXQeBxjqpx3hhiINGiLQRQ8K/A7Ng2cycS792BI3xoaEIalUUApSNcW/rgEM118IjU9PcHQMaKz5QoU5GPoUtyyHsCWRygP+7C/pn4zMQY62e9Ezly7gLx6FHqHbBy7HO3UfjBpVsA67bSgNAZAizRY2aqJ2XA1BJL6gs8/8ie/VPbJ8ti7ryK6vX6ygJmXejlDOBJPZSx1IlQuSYwbdumzG+MwTUtXd2SlwCJpSFipyk8ghAYdh5hEWPKW1LXVIMG2VxQEDqw6LOlittXm8OUPPkDiOi9ByyJHOLLAhMw2E3pMOWHK3xp3szE1hqQCjGP6oQ9kGXjcBqWzsMWpBM0jqVNohaVb8U9GdiqA9W4gJurFciz6ujL5PG4tcmnGsRN8q5jXzLmW2DI/Jx9KcxuQeHzpPv+bJT5NvStl0ShzOFMaCLqHe8yZc2HsePQxjAsGgH6aqzBHphM8nCV41qEKV+IK7ZIomu8WUcMjprI/tg42UFLVckMHM8z4Hze/PAPQGpjwzqeA6VFeABRWt4JDmF2qaMTKJai1clCvOiBsEaJ2h4zOFUiMMGlKDt+oCwcmkSPFXh26WMTM4SsD8SUJj8wgt3ijdyUXSHZScjbyZJmwQ9f0tMUMJ1k07uvMZymeqsHNZa+uN3ARE=
